"""init

Revision ID: 91142aa0466b
Revises: dd45187fd19f
Create Date: 2026-02-22 17:29:22.716917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "91142aa0466b"
down_revision: Union[str, Sequence[str], None] = "dd45187fd19f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shoppinglist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "shoppinglistitem",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("extra_info", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("shopping_list_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shopping_list_id"],
            ["shoppinglist.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shoppinglistitem")
    op.drop_table("shoppinglist")
    # ### end Alembic commands ###
